/**
 * Common-character pinyin table: char → space-separated toneless readings
 * (polyphones carry every reading, frequency-ordered first; ü is written
 * as the keyboard form "v" — "lv", "nv").
 *
 * GENERATED FILE — do not edit by hand. Regenerate with:
 *     npm i --no-save pinyin-pro && node scripts/make-pinyin-data.mjs
 *
 * - Chars: 《现代汉语常用字表》 (1988, 3500 entries here) via
 *   scripts/common-chars-1988.txt, fetched from zispace/hanzi-chars 0.1.2.
 * - Readings: pinyin-pro 3.x (MIT), all readings per char.
 *
 * The table covers the common-character set only: rarer characters fold to
 * themselves (no pinyin matching), which the search core treats as absent
 * data, never as an error. {@module dsh-tui-find/core/pinyin-data}
 */
export const PINYIN_READINGS: Readonly<Record<string, string>> = {
  '一': 'yi',
  '丁': 'ding zheng',
  '七': 'qi',
  '万': 'wan mo',
  '丈': 'zhang',
  '三': 'san',
  '上': 'shang',
  '下': 'xia',
  '不': 'bu fou',
  '与': 'yu',
  '丐': 'gai',
  '丑': 'chou',
  '专': 'zhuan',
  '且': 'qie ju',
  '世': 'shi',
  '丘': 'qiu',
  '丙': 'bing',
  '业': 'ye',
  '丛': 'cong',
  '东': 'dong',
  '丝': 'si',
  '丢': 'diu',
  '两': 'liang',
  '严': 'yan',
  '丧': 'sang',
  '个': 'ge',
  '中': 'zhong',
  '丰': 'feng',
  '串': 'chuan',
  '临': 'lin',
  '丸': 'wan',
  '丹': 'dan',
  '为': 'wei',
  '主': 'zhu',
  '丽': 'li',
  '举': 'ju',
  '乃': 'nai',
  '久': 'jiu',
  '么': 'me mo ma yao',
  '义': 'yi',
  '之': 'zhi',
  '乌': 'wu',
  '乍': 'zha',
  '乎': 'hu',
  '乏': 'fa',
  '乐': 'le yue yao lao',
  '乒': 'ping',
  '乓': 'pang',
  '乔': 'qiao',
  '乖': 'guai',
  '乘': 'cheng sheng',
  '乙': 'yi',
  '九': 'jiu',
  '乞': 'qi',
  '也': 'ye',
  '习': 'xi',
  '乡': 'xiang',
  '书': 'shu',
  '买': 'mai',
  '乱': 'luan',
  '乳': 'ru',
  '乾': 'qian gan',
  '了': 'le liao',
  '予': 'yu',
  '争': 'zheng',
  '事': 'shi',
  '二': 'er',
  '于': 'yu',
  '亏': 'kui',
  '云': 'yun',
  '互': 'hu',
  '五': 'wu',
  '井': 'jing',
  '亚': 'ya',
  '些': 'xie suo',
  '亡': 'wang wu',
  '交': 'jiao',
  '亥': 'hai',
  '亦': 'yi',
  '产': 'chan',
  '亩': 'mu',
  '享': 'xiang',
  '京': 'jing',
  '亭': 'ting',
  '亮': 'liang',
  '亲': 'qin qing',
  '人': 'ren',
  '亿': 'yi',
  '什': 'shen shi',
  '仁': 'ren',
  '仅': 'jin',
  '仆': 'pu',
  '仇': 'chou qiu',
  '今': 'jin',
  '介': 'jie',
  '仍': 'reng',
  '从': 'cong',
  '仑': 'lun',
  '仓': 'cang',
  '仔': 'zai zi',
  '他': 'ta',
  '仗': 'zhang',
  '付': 'fu',
  '仙': 'xian',
  '代': 'dai',
  '令': 'ling',
  '以': 'yi',
  '仪': 'yi',
  '们': 'men',
  '仰': 'yang ang',
  '仲': 'zhong',
  '件': 'jian',
  '价': 'jia jie',
  '任': 'ren',
  '份': 'fen bin',
  '仿': 'fang',
  '企': 'qi',
  '伊': 'yi',
  '伍': 'wu',
  '伏': 'fu',
  '伐': 'fa',
  '休': 'xiu xu',
  '众': 'zhong',
  '优': 'you',
  '伙': 'huo',
  '会': 'hui kuai',
  '伞': 'san',
  '伟': 'wei',
  '传': 'chuan zhuan',
  '伤': 'shang',
  '伦': 'lun',
  '伪': 'wei',
  '伯': 'bo bai',
  '估': 'gu',
  '伴': 'ban',
  '伶': 'ling',
  '伸': 'shen',
  '伺': 'si ci',
  '似': 'si shi',
  '佃': 'dian tian',
  '但': 'dan',
  '位': 'wei',
  '低': 'di',
  '住': 'zhu',
  '佑': 'you',
  '体': 'ti',
  '何': 'he',
  '余': 'yu',
  '佛': 'fo fu bi bo',
  '作': 'zuo',
  '你': 'ni',
  '佣': 'yong',
  '佩': 'pei',
  '佳': 'jia',
  '使': 'shi',
  '侄': 'zhi',
  '侈': 'chi',
  '例': 'li',
  '侍': 'shi',
  '供': 'gong',
  '依': 'yi',
  '侠': 'xia',
  '侣': 'lv',
  '侥': 'jiao yao',
  '侦': 'zhen',
  '侧': 'ce ze zhai',
  '侨': 'qiao',
  '侮': 'wu',
  '侯': 'hou',
  '侵': 'qin',
  '便': 'bian pian',
  '促': 'cu',
  '俄': 'e',
  '俊': 'jun',
  '俏': 'qiao xiao',
  '俐': 'li',
  '俗': 'su',
  '俘': 'fu',
  '保': 'bao',
  '信': 'xin shen',
  '俩': 'lia liang',
  '俭': 'jian',
  '修': 'xiu',
  '俯': 'fu',
  '俱': 'ju',
  '俺': 'an',
  '倍': 'bei',
  '倒': 'dao',
  '倔': 'jue',
  '倘': 'tang chang',
  '候': 'hou',
  '倚': 'yi',
  '借': 'jie',
  '倡': 'chang',
  '倦': 'juan',
  '债': 'zhai',
  '值': 'zhi',
  '倾': 'qing',
  '假': 'jia',
  '偎': 'wei',
  '偏': 'pian',
  '做': 'zuo',
  '停': 'ting',
  '健': 'jian',
  '偶': 'ou',
  '偷': 'tou',
  '偿': 'chang',
  '傀': 'kui gui',
  '傅': 'fu',
  '傍': 'bang',
  '储': 'chu',
  '催': 'cui',
  '傲': 'ao',
  '傻': 'sha',
  '像': 'xiang',
  '僚': 'liao',
  '僧': 'seng',
  '僵': 'jiang',
  '僻': 'pi',
  '儒': 'ru',
  '儡': 'lei',
  '儿': 'er',
  '允': 'yun',
  '元': 'yuan',
  '兄': 'xiong',
  '充': 'chong',
  '兆': 'zhao',
  '先': 'xian',
  '光': 'guang',
  '克': 'ke',
  '免': 'mian',
  '兑': 'dui rui yue',
  '兔': 'tu',
  '党': 'dang',
  '兜': 'dou',
  '兢': 'jing',
  '入': 'ru',
  '全': 'quan',
  '八': 'ba',
  '公': 'gong',
  '六': 'liu lu',
  '兰': 'lan',
  '共': 'gong',
  '关': 'guan',
  '兴': 'xing',
  '兵': 'bing',
  '其': 'qi ji',
  '具': 'ju',
  '典': 'dian',
  '养': 'yang',
  '兼': 'jian',
  '兽': 'shou',
  '冀': 'ji',
  '内': 'nei na',
  '冈': 'gang',
  '册': 'ce',
  '再': 'zai',
  '冒': 'mao mo',
  '冕': 'mian',
  '冗': 'rong',
  '写': 'xie',
  '军': 'jun',
  '农': 'nong',
  '冠': 'guan',
  '冤': 'yuan',
  '冬': 'dong',
  '冯': 'feng ping',
  '冰': 'bing',
  '冲': 'chong',
  '决': 'jue',
  '况': 'kuang',
  '冶': 'ye',
  '冷': 'leng',
  '冻': 'dong',
  '净': 'jing cheng',
  '凄': 'qi',
  '准': 'zhun',
  '凉': 'liang',
  '凌': 'ling',
  '减': 'jian',
  '凑': 'cou',
  '凛': 'lin',
  '凝': 'ning',
  '几': 'ji',
  '凡': 'fan',
  '凤': 'feng',
  '凫': 'fu',
  '凭': 'ping',
  '凯': 'kai',
  '凰': 'huang',
  '凳': 'deng',
  '凶': 'xiong',
  '凸': 'tu',
  '凹': 'ao wa',
  '出': 'chu',
  '击': 'ji',
  '函': 'han',
  '凿': 'zao',
  '刀': 'dao',
  '刁': 'diao',
  '刃': 'ren',
  '分': 'fen',
  '切': 'qie',
  '刊': 'kan',
  '刑': 'xing',
  '划': 'hua',
  '列': 'lie',
  '刘': 'liu',
  '则': 'ze',
  '刚': 'gang',
  '创': 'chuang',
  '初': 'chu',
  '删': 'shan',
  '判': 'pan',
  '刨': 'pao bao',
  '利': 'li',
  '别': 'bie',
  '刮': 'gua',
  '到': 'dao',
  '制': 'zhi',
  '刷': 'shua',
  '券': 'quan xuan',
  '刹': 'cha sha',
  '刺': 'ci',
  '刻': 'ke',
  '刽': 'gui',
  '剂': 'ji',
  '剃': 'ti',
  '削': 'xiao xue',
  '前': 'qian',
  '剑': 'jian',
  '剔': 'ti',
  '剖': 'pou',
  '剥': 'bao bo',
  '剧': 'ju',
  '剩': 'sheng',
  '剪': 'jian',
  '副': 'fu',
  '割': 'ge',
  '剿': 'jiao chao',
  '劈': 'pi',
  '力': 'li',
  '劝': 'quan',
  '办': 'ban',
  '功': 'gong',
  '加': 'jia',
  '务': 'wu',
  '劣': 'lie',
  '动': 'dong',
  '助': 'zhu chu',
  '努': 'nu',
  '劫': 'jie',
  '励': 'li',
  '劲': 'jin jing',
  '劳': 'lao',
  '势': 'shi',
  '勃': 'bo bei',
  '勇': 'yong',
  '勉': 'mian',
  '勋': 'xun',
  '勒': 'le lei',
  '勘': 'kan',
  '募': 'mu',
  '勤': 'qin',
  '勺': 'shao',
  '勾': 'gou',
  '勿': 'wu',
  '匀': 'yun',
  '包': 'bao',
  '匆': 'cong',
  '匈': 'xiong',
  '匕': 'bi',
  '化': 'hua',
  '北': 'bei',
  '匙': 'chi shi',
  '匠': 'jiang',
  '匣': 'xia',
  '匪': 'fei',
  '匹': 'pi',
  '区': 'qu ou',
  '医': 'yi',
  '匾': 'bian',
  '匿': 'ni',
  '十': 'shi',
  '千': 'qian',
  '升': 'sheng',
  '午': 'wu',
  '半': 'ban',
  '华': 'hua',
  '协': 'xie',
  '卑': 'bei',
  '卒': 'zu cu',
  '卓': 'zhuo',
  '单': 'dan shan chan',
  '卖': 'mai',
  '南': 'nan na',
  '博': 'bo',
  '卜': 'bu bo pu',
  '占': 'zhan',
  '卡': 'ka qia',
  '卢': 'lu',
  '卤': 'lu',
  '卦': 'gua',
  '卧': 'wo',
  '卫': 'wei',
  '印': 'yin',
  '危': 'wei',
  '即': 'ji',
  '却': 'que',
  '卵': 'luan',
  '卷': 'juan',
  '卸': 'xie',
  '卿': 'qing',
  '厂': 'chang an han',
  '厅': 'ting',
  '历': 'li',
  '厉': 'li',
  '压': 'ya',
  '厌': 'yan',
  '厕': 'ce',
  '厘': 'li',
  '厚': 'hou',
  '原': 'yuan',
  '厢': 'xiang',
  '厦': 'sha xia',
  '厨': 'chu',
  '去': 'qu',
  '县': 'xian xuan',
  '叁': 'san',
  '参': 'can shen cen san',
  '又': 'you',
  '叉': 'cha',
  '及': 'ji',
  '友': 'you',
  '双': 'shuang',
  '反': 'fan',
  '发': 'fa',
  '叔': 'shu',
  '取': 'qu',
  '受': 'shou',
  '变': 'bian',
  '叙': 'xu',
  '叛': 'pan',
  '叠': 'die',
  '口': 'kou',
  '古': 'gu',
  '句': 'ju gou',
  '另': 'ling',
  '叨': 'dao tao',
  '只': 'zhi',
  '叫': 'jiao',
  '召': 'zhao shao',
  '叭': 'ba',
  '叮': 'ding',
  '可': 'ke',
  '台': 'tai',
  '史': 'shi',
  '右': 'you',
  '叶': 'ye xie',
  '号': 'hao',
  '司': 'si',
  '叹': 'tan',
  '叼': 'diao',
  '叽': 'ji',
  '吁': 'xu yu',
  '吃': 'chi',
  '各': 'ge',
  '吆': 'yao',
  '合': 'he ge',
  '吉': 'ji',
  '吊': 'diao',
  '同': 'tong',
  '名': 'ming',
  '后': 'hou',
  '吏': 'li',
  '吐': 'tu',
  '向': 'xiang',
  '吓': 'xia he',
  '吕': 'lv',
  '吗': 'ma',
  '君': 'jun',
  '吝': 'lin',
  '吞': 'tun',
  '吟': 'yin',
  '吠': 'fei',
  '否': 'fou pi',
  '吧': 'ba',
  '吨': 'dun',
  '吩': 'fen',
  '含': 'han',
  '听': 'ting',
  '吭': 'keng hang',
  '吮': 'shun',
  '启': 'qi',
  '吱': 'zhi zi',
  '吴': 'wu',
  '吵': 'chao',
  '吸': 'xi',
  '吹': 'chui',
  '吻': 'wen',
  '吼': 'hou',
  '呀': 'ya',
  '呆': 'dai',
  '呈': 'cheng',
  '告': 'gao',
  '呐': 'na',
  '呕': 'ou',
  '员': 'yuan yun',
  '呛': 'qiang',
  '呜': 'wu',
  '呢': 'ne ni',
  '周': 'zhou',
  '味': 'wei',
  '呵': 'he a',
  '呻': 'shen',
  '呼': 'hu',
  '命': 'ming',
  '咆': 'pao',
  '和': 'he huo hu',
  '咏': 'yong',
  '咐': 'fu',
  '咒': 'zhou',
  '咕': 'gu',
  '咖': 'ka ga',
  '咙': 'long',
  '咧': 'lie',
  '咨': 'zi',
  '咪': 'mi',
  '咬': 'yao',
  '咱': 'zan za',
  '咳': 'hai ke',
  '咸': 'xian',
  '咽': 'yan ye',
  '哀': 'ai',
  '品': 'pin',
  '哄': 'hong',
  '哆': 'duo',
  '哈': 'ha',
  '响': 'xiang',
  '哎': 'ai',
  '哑': 'ya',
  '哗': 'hua',
  '哟': 'yo',
  '哥': 'ge',
  '哨': 'shao',
  '哩': 'li',
  '哪': 'na nai ne nei',
  '哭': 'ku',
  '哮': 'xiao',
  '哲': 'zhe',
  '哺': 'bu',
  '哼': 'heng hng',
  '唁': 'yan',
  '唆': 'suo',
  '唇': 'chun',
  '唉': 'ai',
  '唐': 'tang',
  '唠': 'lao',
  '唤': 'huan',
  '唧': 'ji',
  '唬': 'hu xia',
  '售': 'shou',
  '唯': 'wei',
  '唱': 'chang',
  '唾': 'tuo',
  '啃': 'ken',
  '啄': 'zhuo',
  '商': 'shang',
  '啊': 'a',
  '啡': 'fei',
  '啤': 'pi',
  '啥': 'sha',
  '啦': 'la',
  '啰': 'luo',
  '啸': 'xiao',
  '啼': 'ti',
  '喂': 'wei',
  '善': 'shan',
  '喇': 'la',
  '喉': 'hou',
  '喊': 'han',
  '喘': 'chuan',
  '喜': 'xi',
  '喝': 'he ye',
  '喧': 'xuan',
  '喳': 'zha cha',
  '喷': 'pen',
  '喻': 'yu',
  '嗅': 'xiu',
  '嗓': 'sang',
  '嗜': 'shi',
  '嗡': 'weng',
  '嗤': 'chi',
  '嗦': 'suo',
  '嗽': 'sou',
  '嘀': 'di',
  '嘁': 'qi',
  '嘉': 'jia',
  '嘱': 'zhu',
  '嘲': 'chao zhao',
  '嘴': 'zui',
  '嘶': 'si',
  '嘹': 'liao',
  '嘿': 'hei mo',
  '器': 'qi',
  '噩': 'e',
  '噪': 'zao',
  '嚎': 'hao',
  '嚣': 'ao xiao',
  '嚷': 'rang',
  '嚼': 'jiao jue',
  '囊': 'nang',
  '囚': 'qiu',
  '四': 'si',
  '回': 'hui',
  '因': 'yin',
  '团': 'tuan',
  '囤': 'tun dun',
  '园': 'yuan',
  '困': 'kun',
  '囱': 'cong',
  '围': 'wei',
  '固': 'gu',
  '国': 'guo',
  '图': 'tu',
  '圃': 'pu',
  '圆': 'yuan',
  '圈': 'quan juan',
  '土': 'tu',
  '圣': 'sheng',
  '在': 'zai',
  '地': 'di de',
  '场': 'chang',
  '圾': 'ji',
  '址': 'zhi',
  '均': 'jun',
  '坊': 'fang',
  '坎': 'kan',
  '坏': 'huai pei pi',
  '坐': 'zuo',
  '坑': 'keng',
  '块': 'kuai',
  '坚': 'jian',
  '坛': 'tan',
  '坝': 'ba',
  '坞': 'wu',
  '坟': 'fen',
  '坠': 'zhui',
  '坡': 'po',
  '坤': 'kun',
  '坦': 'tan',
  '坪': 'ping',
  '坯': 'pi',
  '坷': 'ke',
  '垂': 'chui',
  '垃': 'la',
  '垄': 'long',
  '型': 'xing',
  '垒': 'lei',
  '垛': 'duo',
  '垢': 'gou',
  '垦': 'ken',
  '垫': 'dian',
  '垮': 'kua',
  '埂': 'geng',
  '埃': 'ai',
  '埋': 'mai man',
  '城': 'cheng',
  '域': 'yu',
  '埠': 'bu',
  '培': 'pei',
  '基': 'ji',
  '堂': 'tang',
  '堆': 'dui',
  '堕': 'duo hui',
  '堡': 'bao bu pu',
  '堤': 'di',
  '堪': 'kan',
  '堰': 'yan',
  '堵': 'du',
  '塌': 'ta',
  '塑': 'su',
  '塔': 'ta',
  '塘': 'tang',
  '塞': 'sai se',
  '填': 'tian zhen',
  '境': 'jing',
  '墅': 'shu',
  '墓': 'mu',
  '墙': 'qiang',
  '增': 'zeng',
  '墨': 'mo',
  '墩': 'dun',
  '壁': 'bi',
  '壕': 'hao',
  '壤': 'rang',
  '士': 'shi',
  '壮': 'zhuang',
  '声': 'sheng',
  '壳': 'ke qiao',
  '壶': 'hu',
  '壹': 'yi',
  '处': 'chu',
  '备': 'bei',
  '复': 'fu',
  '夏': 'xia',
  '夕': 'xi',
  '外': 'wai',
  '多': 'duo',
  '夜': 'ye',
  '够': 'gou',
  '大': 'da dai',
  '天': 'tian',
  '太': 'tai',
  '夫': 'fu',
  '夭': 'yao',
  '央': 'yang',
  '夯': 'hang ben',
  '失': 'shi',
  '头': 'tou',
  '夷': 'yi',
  '夸': 'kua',
  '夹': 'jia ga xia',
  '夺': 'duo',
  '奄': 'yan',
  '奇': 'qi ji',
  '奈': 'nai',
  '奉': 'feng',
  '奋': 'fen',
  '奏': 'zou',
  '契': 'qi qie xie',
  '奔': 'ben',
  '奕': 'yi',
  '奖': 'jiang',
  '套': 'tao',
  '奠': 'dian',
  '奢': 'she',
  '奥': 'ao yu',
  '女': 'nv ru',
  '奴': 'nu',
  '奶': 'nai',
  '奸': 'jian',
  '她': 'ta jie',
  '好': 'hao',
  '如': 'ru',
  '妄': 'wang',
  '妆': 'zhuang',
  '妇': 'fu',
  '妈': 'ma',
  '妒': 'du',
  '妓': 'ji',
  '妖': 'yao',
  '妙': 'miao',
  '妥': 'tuo',
  '妨': 'fang',
  '妹': 'mei',
  '妻': 'qi',
  '姆': 'mu',
  '姊': 'zi',
  '始': 'shi',
  '姐': 'jie',
  '姑': 'gu',
  '姓': 'xing',
  '委': 'wei',
  '姚': 'yao',
  '姜': 'jiang',
  '姥': 'lao mu',
  '姨': 'yi',
  '姻': 'yin',
  '姿': 'zi',
  '威': 'wei',
  '娃': 'wa',
  '娄': 'lou',
  '娇': 'jiao',
  '娘': 'niang',
  '娜': 'na nuo',
  '娩': 'mian',
  '娱': 'yu',
  '娶': 'qu',
  '婆': 'po',
  '婉': 'wan',
  '婚': 'hun',
  '婴': 'ying',
  '婶': 'shen',
  '婿': 'xu',
  '媒': 'mei',
  '媚': 'mei',
  '媳': 'xi',
  '嫁': 'jia',
  '嫂': 'sao',
  '嫉': 'ji',
  '嫌': 'xian',
  '嫡': 'di',
  '嫩': 'nen',
  '嬉': 'xi',
  '子': 'zi',
  '孔': 'kong',
  '孕': 'yun',
  '字': 'zi',
  '存': 'cun',
  '孙': 'sun xun',
  '孝': 'xiao',
  '孟': 'meng',
  '季': 'ji',
  '孤': 'gu',
  '学': 'xue',
  '孩': 'hai',
  '孵': 'fu',
  '孽': 'nie',
  '宁': 'ning',
  '它': 'ta',
  '宅': 'zhai',
  '宇': 'yu',
  '守': 'shou',
  '安': 'an',
  '宋': 'song',
  '完': 'wan',
  '宏': 'hong',
  '宗': 'zong',
  '官': 'guan',
  '宙': 'zhou',
  '定': 'ding',
  '宛': 'wan yuan',
  '宜': 'yi',
  '宝': 'bao',
  '实': 'shi',
  '宠': 'chong',
  '审': 'shen',
  '客': 'ke',
  '宣': 'xuan',
  '室': 'shi',
  '宦': 'huan',
  '宪': 'xian',
  '宫': 'gong',
  '宰': 'zai',
  '害': 'hai',
  '宴': 'yan',
  '宵': 'xiao',
  '家': 'jia jie',
  '容': 'rong',
  '宽': 'kuan',
  '宾': 'bin',
  '宿': 'su xiu',
  '寂': 'ji',
  '寄': 'ji',
  '密': 'mi',
  '寇': 'kou',
  '富': 'fu',
  '寒': 'han',
  '寓': 'yu',
  '寝': 'qin',
  '寞': 'mo',
  '察': 'cha',
  '寡': 'gua',
  '寥': 'liao',
  '寨': 'zhai',
  '寸': 'cun',
  '对': 'dui',
  '寺': 'si',
  '寻': 'xun',
  '导': 'dao',
  '寿': 'shou',
  '封': 'feng',
  '射': 'she ye yi',
  '将': 'jiang qiang',
  '尉': 'wei yu',
  '尊': 'zun',
  '小': 'xiao',
  '少': 'shao',
  '尔': 'er',
  '尖': 'jian',
  '尘': 'chen',
  '尚': 'shang',
  '尝': 'chang',
  '尤': 'you',
  '就': 'jiu',
  '尸': 'shi',
  '尺': 'chi che',
  '尼': 'ni',
  '尽': 'jin',
  '尾': 'wei yi',
  '尿': 'niao sui',
  '局': 'ju',
  '屁': 'pi',
  '层': 'ceng',
  '居': 'ju',
  '屈': 'qu',
  '屉': 'ti',
  '届': 'jie',
  '屋': 'wu',
  '屎': 'shi',
  '屏': 'ping bing',
  '屑': 'xie',
  '展': 'zhan',
  '属': 'shu zhu',
  '屠': 'tu',
  '屡': 'lv',
  '履': 'lv',
  '屯': 'tun zhun',
  '山': 'shan',
  '屹': 'yi',
  '屿': 'yu',
  '岁': 'sui',
  '岂': 'qi kai',
  '岔': 'cha',
  '岖': 'qu',
  '岗': 'gang',
  '岛': 'dao',
  '岩': 'yan',
  '岭': 'ling',
  '岳': 'yue',
  '岸': 'an',
  '峡': 'xia',
  '峦': 'luan',
  '峭': 'qiao',
  '峰': 'feng',
  '峻': 'jun',
  '崇': 'chong',
  '崎': 'qi',
  '崔': 'cui',
  '崖': 'ya',
  '崩': 'beng',
  '崭': 'zhan chan',
  '嵌': 'qian kan',
  '巍': 'wei',
  '川': 'chuan',
  '州': 'zhou',
  '巡': 'xun',
  '巢': 'chao',
  '工': 'gong',
  '左': 'zuo',
  '巧': 'qiao',
  '巨': 'ju',
  '巩': 'gong',
  '巫': 'wu',
  '差': 'cha chai ci',
  '己': 'ji',
  '已': 'yi',
  '巴': 'ba',
  '巷': 'xiang hang',
  '巾': 'jin',
  '币': 'bi',
  '市': 'shi',
  '布': 'bu',
  '帅': 'shuai',
  '帆': 'fan',
  '师': 'shi',
  '希': 'xi',
  '帐': 'zhang',
  '帕': 'pa',
  '帖': 'tie',
  '帘': 'lian',
  '帚': 'zhou',
  '帜': 'zhi',
  '帝': 'di',
  '带': 'dai',
  '席': 'xi',
  '帮': 'bang',
  '常': 'chang',
  '帽': 'mao',
  '幅': 'fu',
  '幌': 'huang',
  '幔': 'man',
  '幕': 'mu',
  '幢': 'zhuang chuang',
  '干': 'gan',
  '平': 'ping',
  '年': 'nian',
  '并': 'bing',
  '幸': 'xing',
  '幻': 'huan',
  '幼': 'you',
  '幽': 'you',
  '广': 'guang an',
  '庄': 'zhuang',
  '庆': 'qing',
  '庇': 'bi',
  '床': 'chuang',
  '序': 'xu',
  '庐': 'lu',
  '库': 'ku',
  '应': 'ying',
  '底': 'di de',
  '店': 'dian',
  '庙': 'miao',
  '府': 'fu',
  '庞': 'pang',
  '废': 'fei',
  '度': 'du duo',
  '座': 'zuo',
  '庭': 'ting',
  '庵': 'an',
  '庶': 'shu',
  '康': 'kang',
  '庸': 'yong',
  '廉': 'lian',
  '廊': 'lang',
  '廓': 'kuo',
  '延': 'yan',
  '廷': 'ting',
  '建': 'jian',
  '开': 'kai',
  '异': 'yi',
  '弃': 'qi',
  '弄': 'nong long',
  '弊': 'bi',
  '式': 'shi',
  '弓': 'gong',
  '引': 'yin',
  '弛': 'chi',
  '弟': 'di ti tui',
  '张': 'zhang',
  '弥': 'mi',
  '弦': 'xian',
  '弧': 'hu',
  '弯': 'wan',
  '弱': 'ruo',
  '弹': 'tan dan',
  '强': 'qiang jiang',
  '归': 'gui',
  '当': 'dang',
  '录': 'lu',
  '形': 'xing',
  '彤': 'tong',
  '彩': 'cai',
  '彪': 'biao',
  '彬': 'bin',
  '彭': 'peng bang',
  '彰': 'zhang',
  '影': 'ying',
  '役': 'yi',
  '彻': 'che',
  '彼': 'bi',
  '往': 'wang',
  '征': 'zheng',
  '径': 'jing',
  '待': 'dai',
  '很': 'hen',
  '徊': 'huai',
  '律': 'lv',
  '徐': 'xu',
  '徒': 'tu',
  '得': 'de dei',
  '徘': 'pai',
  '徙': 'xi',
  '御': 'yu',
  '循': 'xun',
  '微': 'wei',
  '德': 'de',
  '徽': 'hui',
  '心': 'xin',
  '必': 'bi',
  '忆': 'yi',
  '忌': 'ji',
  '忍': 'ren',
  '志': 'zhi',
  '忘': 'wang',
  '忙': 'mang',
  '忠': 'zhong',
  '忧': 'you',
  '快': 'kuai',
  '忱': 'chen',
  '念': 'nian',
  '忽': 'hu',
  '忿': 'fen',
  '怀': 'huai',
  '态': 'tai',
  '怎': 'zen',
  '怒': 'nu',
  '怔': 'zheng',
  '怕': 'pa',
  '怖': 'bu',
  '怜': 'lian',
  '思': 'si sai',
  '怠': 'dai',
  '急': 'ji',
  '性': 'xing',
  '怨': 'yuan',
  '怪': 'guai',
  '怯': 'qie',
  '总': 'zong',
  '恃': 'shi',
  '恋': 'lian',
  '恍': 'huang',
  '恐': 'kong',
  '恒': 'heng',
  '恕': 'shu',
  '恢': 'hui',
  '恤': 'xu',
  '恨': 'hen',
  '恩': 'en',
  '恬': 'tian',
  '恭': 'gong',
  '息': 'xi',
  '恰': 'qia',
  '恳': 'ken',
  '恶': 'e wu',
  '恼': 'nao',
  '悄': 'qiao',
  '悉': 'xi',
  '悍': 'han',
  '悔': 'hui',
  '悟': 'wu',
  '悠': 'you',
  '患': 'huan',
  '悦': 'yue',
  '您': 'nin',
  '悬': 'xuan',
  '悯': 'min',
  '悲': 'bei',
  '悴': 'cui',
  '悼': 'dao',
  '情': 'qing',
  '惊': 'jing',
  '惋': 'wan',
  '惑': 'huo',
  '惕': 'ti',
  '惜': 'xi',
  '惠': 'hui',
  '惦': 'dian',
  '惧': 'ju',
  '惨': 'can',
  '惩': 'cheng',
  '惫': 'bei',
  '惭': 'can',
  '惯': 'guan',
  '惰': 'duo',
  '想': 'xiang',
  '惶': 'huang',
  '惹': 're',
  '愁': 'chou',
  '愈': 'yu',
  '愉': 'yu tou',
  '意': 'yi',
  '愕': 'e',
  '愚': 'yu',
  '感': 'gan',
  '愤': 'fen',
  '愧': 'kui',
  '愿': 'yuan',
  '慈': 'ci',
  '慌': 'huang',
  '慎': 'shen',
  '慕': 'mu',
  '慢': 'man',
  '慧': 'hui',
  '慨': 'kai',
  '慰': 'wei',
  '慷': 'kang',
  '憋': 'bie',
  '憎': 'zeng',
  '憔': 'qiao',
  '憨': 'han',
  '憾': 'han',
  '懂': 'dong',
  '懈': 'xie',
  '懊': 'ao',
  '懒': 'lan',
  '懦': 'nuo',
  '戈': 'ge',
  '戏': 'xi hu',
  '成': 'cheng',
  '我': 'wo',
  '戒': 'jie',
  '或': 'huo',
  '战': 'zhan',
  '戚': 'qi',
  '截': 'jie',
  '戳': 'chuo',
  '戴': 'dai',
  '户': 'hu',
  '房': 'fang',
  '所': 'suo',
  '扁': 'bian pian',
  '扇': 'shan',
  '手': 'shou',
  '才': 'cai',
  '扎': 'zha za',
  '扑': 'pu',
  '扒': 'ba pa',
  '打': 'da',
  '扔': 'reng',
  '托': 'tuo',
  '扛': 'kang gang',
  '扣': 'kou',
  '执': 'zhi',
  '扩': 'kuo',
  '扫': 'sao',
  '扬': 'yang',
  '扭': 'niu',
  '扮': 'ban',
  '扯': 'che',
  '扰': 'rao',
  '扳': 'ban pan',
  '扶': 'fu',
  '批': 'pi',
  '扼': 'e',
  '找': 'zhao',
  '承': 'cheng',
  '技': 'ji',
  '抄': 'chao',
  '把': 'ba',
  '抑': 'yi',
  '抒': 'shu',
  '抓': 'zhua',
  '投': 'tou',
  '抖': 'dou',
  '抗': 'kang',
  '折': 'zhe she',
  '抚': 'fu',
  '抛': 'pao',
  '抠': 'kou',
  '抡': 'lun',
  '抢': 'qiang cheng',
  '护': 'hu',
  '报': 'bao',
  '披': 'pi',
  '抬': 'tai',
  '抱': 'bao',
  '抵': 'di',
  '抹': 'mo ma',
  '押': 'ya',
  '抽': 'chou',
  '拂': 'fu bi',
  '拄': 'zhu',
  '担': 'dan',
  '拆': 'chai ca',
  '拇': 'mu',
  '拉': 'la',
  '拌': 'ban pan',
  '拍': 'pai',
  '拐': 'guai',
  '拒': 'ju',
  '拓': 'tuo ta zhi',
  '拔': 'ba',
  '拖': 'tuo',
  '拗': 'ao niu',
  '拘': 'ju gou',
  '拙': 'zhuo',
  '招': 'zhao',
  '拜': 'bai',
  '拟': 'ni',
  '拢': 'long',
  '拣': 'jian',
  '拥': 'yong',
  '拦': 'lan',
  '拧': 'ning',
  '拨': 'bo',
  '择': 'ze zhai',
  '括': 'kuo gua',
  '拭': 'shi',
  '拯': 'zheng',
  '拱': 'gong',
  '拳': 'quan',
  '拴': 'shuan',
  '拷': 'kao',
  '拼': 'pin',
  '拾': 'shi she',
  '拿': 'na',
  '持': 'chi',
  '挂': 'gua',
  '指': 'zhi',
  '按': 'an',
  '挎': 'kua ku',
  '挑': 'tiao',
  '挖': 'wa',
  '挚': 'zhi',
  '挟': 'xie jia',
  '挠': 'nao',
  '挡': 'dang',
  '挣': 'zheng',
  '挤': 'ji',
  '挥': 'hui',
  '挨': 'ai',
  '挪': 'nuo',
  '挫': 'cuo',
  '振': 'zhen',
  '挺': 'ting',
  '挽': 'wan',
  '捂': 'wu',
  '捅': 'tong',
  '捆': 'kun',
  '捉': 'zhuo',
  '捌': 'ba',
  '捍': 'han',
  '捎': 'shao',
  '捏': 'nie',
  '捐': 'juan',
  '捕': 'bu',
  '捞': 'lao',
  '损': 'sun',
  '捡': 'jian',
  '换': 'huan',
  '捣': 'dao',
  '捧': 'peng',
  '据': 'ju',
  '捶': 'chui',
  '捷': 'jie',
  '捺': 'na',
  '捻': 'nian nie',
  '掀': 'xian',
  '掂': 'dian',
  '授': 'shou',
  '掉': 'diao',
  '掌': 'zhang',
  '掏': 'tao',
  '掐': 'qia',
  '排': 'pai',
  '掖': 'ye',
  '掘': 'jue',
  '掠': 'lve',
  '探': 'tan',
  '接': 'jie',
  '控': 'kong',
  '推': 'tui',
  '掩': 'yan',
  '措': 'cuo',
  '掰': 'bai',
  '掷': 'zhi',
  '掸': 'dan shan',
  '掺': 'chan xian can shan',
  '揉': 'rou',
  '揍': 'zou',
  '描': 'miao',
  '提': 'ti di',
  '插': 'cha',
  '揖': 'yi',
  '握': 'wo',
  '揣': 'chuai tuan zhui',
  '揩': 'kai',
  '揪': 'jiu',
  '揭': 'jie qi',
  '援': 'yuan',
  '揽': 'lan',
  '搀': 'chan',
  '搁': 'ge',
  '搂': 'lou',
  '搅': 'jiao',
  '搏': 'bo',
  '搓': 'cuo',
  '搔': 'sao',
  '搜': 'sou',
  '搞': 'gao',
  '搪': 'tang',
  '搬': 'ban',
  '搭': 'da',
  '携': 'xie',
  '摄': 'she nie',
  '摆': 'bai',
  '摇': 'yao',
  '摊': 'tan',
  '摔': 'shuai',
  '摘': 'zhai',
  '摧': 'cui',
  '摩': 'mo ma',
  '摸': 'mo',
  '摹': 'mo',
  '撇': 'pie',
  '撑': 'cheng',
  '撒': 'sa',
  '撕': 'si',
  '撞': 'zhuang',
  '撤': 'che',
  '撩': 'liao',
  '撬': 'qiao',
  '播': 'bo',
  '撮': 'cuo zuo',
  '撰': 'zhuan',
  '撵': 'nian',
  '撼': 'han',
  '擂': 'lei',
  '擅': 'shan',
  '操': 'cao',
  '擎': 'qing',
  '擒': 'qin',
  '擦': 'ca',
  '攀': 'pan',
  '攒': 'zan cuan',
  '攘': 'rang',
  '支': 'zhi',
  '收': 'shou',
  '改': 'gai',
  '攻': 'gong',
  '放': 'fang',
  '政': 'zheng',
  '故': 'gu',
  '效': 'xiao',
  '敌': 'di',
  '敏': 'min',
  '救': 'jiu',
  '教': 'jiao',
  '敛': 'lian',
  '敞': 'chang',
  '敢': 'gan',
  '散': 'san',
  '敦': 'dun dui',
  '敬': 'jing',
  '数': 'shu shuo',
  '敲': 'qiao',
  '整': 'zheng',
  '敷': 'fu',
  '文': 'wen',
  '斋': 'zhai',
  '斑': 'ban',
  '斗': 'dou',
  '料': 'liao',
  '斜': 'xie',
  '斟': 'zhen',
  '斤': 'jin',
  '斥': 'chi',
  '斧': 'fu',
  '斩': 'zhan',
  '断': 'duan',
  '斯': 'si',
  '新': 'xin',
  '方': 'fang',
  '施': 'shi',
  '旁': 'pang bang',
  '旅': 'lv',
  '旋': 'xuan',
  '族': 'zu',
  '旗': 'qi',
  '无': 'wu mo',
  '既': 'ji',
  '日': 'ri',
  '旦': 'dan',
  '旧': 'jiu',
  '旨': 'zhi',
  '早': 'zao',
  '旬': 'xun',
  '旭': 'xu',
  '旱': 'han',
  '时': 'shi',
  '旷': 'kuang',
  '旺': 'wang',
  '昂': 'ang',
  '昆': 'kun',
  '昌': 'chang',
  '明': 'ming',
  '昏': 'hun',
  '易': 'yi',
  '昔': 'xi',
  '昙': 'tan',
  '星': 'xing',
  '映': 'ying',
  '春': 'chun',
  '昧': 'mei',
  '昨': 'zuo',
  '昭': 'zhao',
  '是': 'shi',
  '昵': 'ni',
  '昼': 'zhou',
  '显': 'xian',
  '晃': 'huang',
  '晋': 'jin',
  '晌': 'shang',
  '晒': 'shai',
  '晓': 'xiao',
  '晕': 'yun',
  '晚': 'wan',
  '晤': 'wu',
  '晦': 'hui',
  '晨': 'chen',
  '普': 'pu',
  '景': 'jing ying',
  '晰': 'xi',
  '晴': 'qing',
  '晶': 'jing',
  '智': 'zhi',
  '晾': 'liang',
  '暂': 'zan',
  '暇': 'xia',
  '暑': 'shu',
  '暖': 'nuan',
  '暗': 'an',
  '暮': 'mu',
  '暴': 'bao pu',
  '曙': 'shu',
  '曲': 'qu',
  '更': 'geng',
  '曹': 'cao',
  '曼': 'man',
  '曾': 'ceng zeng',
  '替': 'ti',
  '最': 'zui',
  '月': 'yue',
  '有': 'you',
  '朋': 'peng',
  '服': 'fu',
  '朗': 'lang',
  '望': 'wang',
  '朝': 'chao zhao',
  '期': 'qi ji',
  '朦': 'meng',
  '木': 'mu',
  '未': 'wei',
  '末': 'mo',
  '本': 'ben',
  '术': 'shu zhu',
  '朱': 'zhu shu',
  '朴': 'pu po piao',
  '朵': 'duo',
  '机': 'ji',
  '朽': 'xiu',
  '杀': 'sha',
  '杂': 'za',
  '权': 'quan',
  '杆': 'gan',
  '杈': 'cha',
  '杉': 'shan sha',
  '李': 'li',
  '杏': 'xing',
  '材': 'cai',
  '村': 'cun',
  '杖': 'zhang',
  '杜': 'du',
  '束': 'shu',
  '杠': 'gang',
  '条': 'tiao',
  '来': 'lai',
  '杨': 'yang',
  '杭': 'hang',
  '杯': 'bei',
  '杰': 'jie',
  '松': 'song',
  '板': 'ban',
  '极': 'ji',
  '构': 'gou',
  '枉': 'wang',
  '析': 'xi',
  '枕': 'zhen',
  '林': 'lin',
  '枚': 'mei',
  '果': 'guo',
  '枝': 'zhi qi',
  '枢': 'shu',
  '枣': 'zao',
  '枪': 'qiang',
  '枫': 'feng',
  '枯': 'ku',
  '架': 'jia',
  '枷': 'jia',
  '柄': 'bing',
  '柏': 'bai bo',
  '某': 'mou',
  '柑': 'gan',
  '柒': 'qi',
  '染': 'ran',
  '柔': 'rou',
  '柜': 'gui ju',
  '柠': 'ning',
  '查': 'cha zha',
  '柬': 'jian',
  '柱': 'zhu',
  '柳': 'liu',
  '柴': 'chai',
  '柿': 'shi',
  '栅': 'shan zha shi ce',
  '标': 'biao',
  '栈': 'zhan',
  '栋': 'dong',
  '栏': 'lan',
  '树': 'shu',
  '栓': 'shuan',
  '栖': 'qi xi',
  '栗': 'li',
  '校': 'xiao jiao',
  '株': 'zhu',
  '样': 'yang',
  '核': 'he hu',
  '根': 'gen',
  '格': 'ge',
  '栽': 'zai',
  '桂': 'gui',
  '桃': 'tao',
  '桅': 'wei',
  '框': 'kuang',
  '案': 'an',
  '桌': 'zhuo',
  '桐': 'tong',
  '桑': 'sang',
  '档': 'dang',
  '桥': 'qiao',
  '桦': 'hua',
  '桨': 'jiang',
  '桩': 'zhuang',
  '桶': 'tong',
  '梁': 'liang',
  '梅': 'mei',
  '梆': 'bang',
  '梗': 'geng',
  '梢': 'shao sao',
  '梦': 'meng',
  '梧': 'wu',
  '梨': 'li',
  '梭': 'suo',
  '梯': 'ti',
  '械': 'xie',
  '梳': 'shu',
  '检': 'jian',
  '棉': 'mian',
  '棋': 'qi',
  '棍': 'gun hun',
  '棒': 'bang',
  '棕': 'zong',
  '棘': 'ji',
  '棚': 'peng',
  '棠': 'tang',
  '森': 'sen',
  '棱': 'leng ling',
  '棵': 'ke',
  '棺': 'guan',
  '椅': 'yi',
  '植': 'zhi',
  '椎': 'zhui chui',
  '椒': 'jiao',
  '椭': 'tuo',
  '椰': 'ye',
  '椿': 'chun',
  '楔': 'xie',
  '楚': 'chu',
  '楞': 'leng',
  '楣': 'mei',
  '楷': 'kai jie',
  '楼': 'lou',
  '概': 'gai',
  '榄': 'lan',
  '榆': 'yu',
  '榔': 'lang',
  '榕': 'rong',
  '榛': 'zhen',
  '榜': 'bang',
  '榨': 'zha',
  '榴': 'liu',
  '槐': 'huai',
  '槽': 'cao',
  '樊': 'fan',
  '樟': 'zhang',
  '模': 'mo mu',
  '横': 'heng',
  '樱': 'ying',
  '橄': 'gan',
  '橘': 'ju',
  '橙': 'cheng',
  '橡': 'xiang',
  '橱': 'chu',
  '檀': 'tan',
  '檐': 'yan',
  '檩': 'lin',
  '檬': 'meng',
  '欠': 'qian',
  '次': 'ci',
  '欢': 'huan',
  '欣': 'xin',
  '欧': 'ou',
  '欲': 'yu',
  '欺': 'qi',
  '款': 'kuan',
  '歇': 'xie',
  '歉': 'qian',
  '歌': 'ge',
  '止': 'zhi',
  '正': 'zheng',
  '此': 'ci',
  '步': 'bu',
  '武': 'wu',
  '歧': 'qi',
  '歪': 'wai',
  '歹': 'dai',
  '死': 'si',
  '歼': 'jian',
  '殃': 'yang',
  '殉': 'xun',
  '殊': 'shu',
  '残': 'can',
  '殖': 'zhi shi',
  '殴': 'ou',
  '段': 'duan',
  '殷': 'yin yan',
  '殿': 'dian',
  '毁': 'hui',
  '毅': 'yi',
  '母': 'mu',
  '每': 'mei',
  '毒': 'du dai',
  '比': 'bi',
  '毕': 'bi',
  '毙': 'bi',
  '毛': 'mao',
  '毡': 'zhan',
  '毫': 'hao',
  '毯': 'tan',
  '氏': 'shi zhi',
  '民': 'min',
  '氓': 'mang meng',
  '气': 'qi',
  '氛': 'fen',
  '氢': 'qing',
  '氧': 'yang',
  '氨': 'an',
  '氮': 'dan',
  '氯': 'lv',
  '水': 'shui',
  '永': 'yong',
  '汁': 'zhi',
  '求': 'qiu',
  '汇': 'hui',
  '汉': 'han',
  '汗': 'han',
  '汛': 'xun',
  '汞': 'gong',
  '江': 'jiang',
  '池': 'chi',
  '污': 'wu',
  '汤': 'tang shang',
  '汪': 'wang',
  '汰': 'tai',
  '汹': 'xiong',
  '汽': 'qi',
  '沃': 'wo',
  '沈': 'shen chen',
  '沉': 'chen',
  '沐': 'mu',
  '沙': 'sha',
  '沛': 'pei',
  '沟': 'gou',
  '没': 'mei mo',
  '沥': 'li',
  '沦': 'lun',
  '沧': 'cang',
  '沪': 'hu',
  '沫': 'mo',
  '沮': 'ju',
  '河': 'he',
  '沸': 'fei',
  '油': 'you',
  '治': 'zhi',
  '沼': 'zhao',
  '沽': 'gu',
  '沾': 'zhan',
  '沿': 'yan',
  '泄': 'xie yi',
  '泉': 'quan',
  '泊': 'bo po',
  '泌': 'mi bi',
  '法': 'fa',
  '泛': 'fan',
  '泞': 'ning',
  '泡': 'pao',
  '波': 'bo',
  '泣': 'qi',
  '泥': 'ni',
  '注': 'zhu',
  '泪': 'lei',
  '泰': 'tai',
  '泳': 'yong',
  '泵': 'beng',
  '泻': 'xie',
  '泼': 'po',
  '泽': 'ze shi',
  '洁': 'jie',
  '洋': 'yang',
  '洒': 'sa xi',
  '洗': 'xi xian',
  '洛': 'luo',
  '洞': 'dong tong',
  '津': 'jin',
  '洪': 'hong',
  '洲': 'zhou',
  '活': 'huo',
  '洼': 'wa',
  '洽': 'qia',
  '派': 'pai',
  '流': 'liu',
  '浅': 'qian jian',
  '浆': 'jiang',
  '浇': 'jiao',
  '浊': 'zhuo',
  '测': 'ce',
  '济': 'ji',
  '浑': 'hun',
  '浓': 'nong',
  '浙': 'zhe',
  '浦': 'pu',
  '浩': 'hao',
  '浪': 'lang',
  '浮': 'fu',
  '浴': 'yu',
  '海': 'hai',
  '浸': 'jin',
  '涂': 'tu',
  '消': 'xiao',
  '涉': 'she',
  '涌': 'yong chong',
  '涎': 'xian',
  '涕': 'ti',
  '涛': 'tao',
  '涝': 'lao',
  '涡': 'wo guo',
  '涣': 'huan',
  '涤': 'di',
  '润': 'run',
  '涧': 'jian',
  '涨': 'zhang',
  '涩': 'se',
  '涮': 'shuan',
  '涯': 'ya',
  '液': 'ye',
  '涵': 'han',
  '淀': 'dian',
  '淆': 'xiao',
  '淋': 'lin',
  '淌': 'tang chang',
  '淑': 'shu',
  '淘': 'tao',
  '淡': 'dan',
  '淤': 'yu',
  '淫': 'yin',
  '淮': 'huai',
  '深': 'shen',
  '淳': 'chun zhun',
  '混': 'hun',
  '淹': 'yan',
  '添': 'tian',
  '清': 'qing',
  '渊': 'yuan',
  '渐': 'jian',
  '渔': 'yu',
  '渗': 'shen',
  '渠': 'qu ju',
  '渡': 'du',
  '渣': 'zha',
  '渤': 'bo',
  '温': 'wen',
  '港': 'gang jiang',
  '渴': 'ke',
  '游': 'you',
  '渺': 'miao',
  '湃': 'pai',
  '湖': 'hu',
  '湘': 'xiang',
  '湾': 'wan',
  '湿': 'shi',
  '溃': 'kui hui',
  '溅': 'jian',
  '溉': 'gai',
  '源': 'yuan',
  '溜': 'liu',
  '溢': 'yi',
  '溪': 'xi',
  '溯': 'su',
  '溶': 'rong',
  '溺': 'ni niao',
  '滋': 'zi',
  '滑': 'hua',
  '滓': 'zi',
  '滔': 'tao',
  '滚': 'gun',
  '滞': 'zhi',
  '满': 'man',
  '滤': 'lv',
  '滥': 'lan',
  '滨': 'bin',
  '滩': 'tan',
  '滴': 'di',
  '漂': 'piao',
  '漆': 'qi',
  '漏': 'lou',
  '漓': 'li',
  '演': 'yan',
  '漠': 'mo',
  '漩': 'xuan',
  '漫': 'man',
  '漱': 'shu',
  '漾': 'yang',
  '潘': 'pan',
  '潜': 'qian',
  '潦': 'liao lao',
  '潭': 'tan',
  '潮': 'chao',
  '澄': 'cheng deng',
  '澈': 'che',
  '澎': 'peng',
  '澜': 'lan',
  '澡': 'zao',
  '澳': 'ao',
  '激': 'ji',
  '濒': 'bin',
  '瀑': 'pu bao',
  '灌': 'guan',
  '火': 'huo',
  '灭': 'mie',
  '灯': 'deng',
  '灰': 'hui',
  '灵': 'ling',
  '灶': 'zao',
  '灸': 'jiu',
  '灼': 'zhuo',
  '灾': 'zai',
  '灿': 'can',
  '炉': 'lu',
  '炊': 'chui',
  '炎': 'yan',
  '炒': 'chao',
  '炕': 'kang',
  '炫': 'xuan',
  '炬': 'ju',
  '炭': 'tan',
  '炮': 'pao bao',
  '炸': 'zha',
  '点': 'dian',
  '炼': 'lian',
  '烁': 'shuo',
  '烂': 'lan',
  '烈': 'lie',
  '烘': 'hong',
  '烙': 'lao luo',
  '烛': 'zhu',
  '烟': 'yan',
  '烤': 'kao',
  '烦': 'fan',
  '烧': 'shao',
  '烫': 'tang',
  '热': 're',
  '烹': 'peng',
  '焊': 'han',
  '焕': 'huan',
  '焙': 'bei',
  '焚': 'fen',
  '焦': 'jiao',
  '焰': 'yan',
  '然': 'ran',
  '煌': 'huang',
  '煎': 'jian',
  '煞': 'sha',
  '煤': 'mei',
  '照': 'zhao',
  '煮': 'zhu',
  '熄': 'xi',
  '熊': 'xiong',
  '熏': 'xun',
  '熔': 'rong',
  '熙': 'xi',
  '熟': 'shu shou',
  '熬': 'ao',
  '燃': 'ran',
  '燎': 'liao',
  '燕': 'yan',
  '燥': 'zao',
  '爆': 'bao',
  '爪': 'zhua zhao',
  '爬': 'pa',
  '爱': 'ai',
  '爵': 'jue',
  '父': 'fu',
  '爷': 'ye',
  '爸': 'ba',
  '爹': 'die',
  '爽': 'shuang',
  '片': 'pian',
  '版': 'ban',
  '牌': 'pai',
  '牍': 'du',
  '牙': 'ya',
  '牛': 'niu',
  '牡': 'mu',
  '牢': 'lao',
  '牧': 'mu',
  '物': 'wu',
  '牲': 'sheng',
  '牵': 'qian',
  '特': 'te',
  '牺': 'xi',
  '犀': 'xi',
  '犁': 'li',
  '犬': 'quan',
  '犯': 'fan',
  '状': 'zhuang',
  '犹': 'you',
  '狂': 'kuang',
  '狈': 'bei',
  '狐': 'hu',
  '狗': 'gou',
  '狞': 'ning',
  '狠': 'hen',
  '狡': 'jiao',
  '独': 'du',
  '狭': 'xia',
  '狮': 'shi',
  '狰': 'zheng',
  '狱': 'yu',
  '狸': 'li',
  '狼': 'lang',
  '猎': 'lie',
  '猖': 'chang',
  '猛': 'meng',
  '猜': 'cai',
  '猩': 'xing',
  '猪': 'zhu',
  '猫': 'mao',
  '猬': 'wei',
  '献': 'xian',
  '猴': 'hou',
  '猾': 'hua',
  '猿': 'yuan',
  '玄': 'xuan',
  '率': 'lv shuai',
  '玉': 'yu',
  '王': 'wang',
  '玖': 'jiu',
  '玛': 'ma',
  '玩': 'wan',
  '玫': 'mei',
  '环': 'huan',
  '现': 'xian',
  '玲': 'ling',
  '玷': 'dian',
  '玻': 'bo',
  '珊': 'shan',
  '珍': 'zhen',
  '珠': 'zhu',
  '班': 'ban',
  '球': 'qiu',
  '琅': 'lang',
  '理': 'li',
  '琉': 'liu',
  '琐': 'suo',
  '琢': 'zhuo zuo',
  '琳': 'lin',
  '琴': 'qin',
  '琼': 'qiong',
  '瑞': 'rui',
  '瑟': 'se',
  '瑰': 'gui',
  '璃': 'li',
  '璧': 'bi',
  '瓜': 'gua',
  '瓢': 'piao',
  '瓣': 'ban',
  '瓤': 'rang',
  '瓦': 'wa',
  '瓮': 'weng',
  '瓶': 'ping',
  '瓷': 'ci',
  '甘': 'gan',
  '甚': 'shen',
  '甜': 'tian',
  '生': 'sheng',
  '甥': 'sheng',
  '用': 'yong',
  '甩': 'shuai',
  '甫': 'fu',
  '田': 'tian',
  '由': 'you',
  '甲': 'jia',
  '申': 'shen',
  '电': 'dian',
  '男': 'nan',
  '甸': 'dian tian sheng',
  '画': 'hua',
  '畅': 'chang',
  '界': 'jie',
  '畏': 'wei',
  '畔': 'pan',
  '留': 'liu',
  '畜': 'chu xu',
  '略': 'lve',
  '畦': 'qi',
  '番': 'fan pan',
  '畴': 'chou',
  '畸': 'ji',
  '疆': 'jiang qiang',
  '疏': 'shu',
  '疑': 'yi ni',
  '疗': 'liao',
  '疙': 'ge yi',
  '疚': 'jiu',
  '疟': 'nve yao',
  '疤': 'ba',
  '疫': 'yi',
  '疮': 'chuang',
  '疯': 'feng',
  '疲': 'pi',
  '疹': 'zhen',
  '疼': 'teng',
  '疾': 'ji',
  '病': 'bing',
  '症': 'zheng',
  '痊': 'quan',
  '痒': 'yang',
  '痕': 'hen',
  '痘': 'dou',
  '痛': 'tong',
  '痢': 'li',
  '痪': 'huan',
  '痰': 'tan',
  '痴': 'chi',
  '痹': 'bi',
  '瘟': 'wen',
  '瘤': 'liu',
  '瘦': 'shou',
  '瘩': 'da',
  '瘪': 'bie',
  '瘫': 'tan',
  '瘸': 'que',
  '瘾': 'yin',
  '癌': 'ai',
  '癞': 'lai',
  '癣': 'xuan',
  '登': 'deng',
  '白': 'bai',
  '百': 'bai',
  '皂': 'zao',
  '的': 'de di',
  '皆': 'jie',
  '皇': 'huang',
  '皮': 'pi',
  '皱': 'zhou',
  '皿': 'min',
  '盅': 'zhong',
  '盆': 'pen',
  '盈': 'ying',
  '益': 'yi',
  '盏': 'zhan',
  '盐': 'yan',
  '监': 'jian',
  '盒': 'he',
  '盔': 'kui',
  '盖': 'gai ge he',
  '盗': 'dao',
  '盘': 'pan',
  '盛': 'sheng cheng',
  '盟': 'meng',
  '目': 'mu',
  '盯': 'ding',
  '盲': 'mang',
  '直': 'zhi',
  '相': 'xiang',
  '盹': 'dun',
  '盼': 'pan',
  '盾': 'dun',
  '省': 'sheng xing',
  '眉': 'mei',
  '看': 'kan',
  '真': 'zhen',
  '眠': 'mian',
  '眨': 'zha',
  '眯': 'mi',
  '眶': 'kuang',
  '眷': 'juan',
  '眼': 'yan',
  '着': 'zhe zhuo zhao',
  '睁': 'zheng',
  '睛': 'jing',
  '睡': 'shui',
  '督': 'du',
  '睦': 'mu',
  '睬': 'cai',
  '睹': 'du',
  '瞄': 'miao',
  '瞎': 'xia',
  '瞒': 'man men',
  '瞧': 'qiao',
  '瞪': 'deng',
  '瞬': 'shun',
  '瞭': 'liao',
  '瞳': 'tong',
  '瞻': 'zhan',
  '矗': 'chu',
  '矛': 'mao',
  '矢': 'shi',
  '知': 'zhi',
  '矩': 'ju',
  '矫': 'jiao',
  '短': 'duan',
  '矮': 'ai',
  '石': 'shi dan',
  '矾': 'fan',
  '矿': 'kuang',
  '码': 'ma',
  '砂': 'sha',
  '砌': 'qi qie',
  '砍': 'kan',
  '研': 'yan',
  '砖': 'zhuan',
  '砚': 'yan',
  '砰': 'peng',
  '破': 'po',
  '砸': 'za',
  '砾': 'li',
  '础': 'chu',
  '硅': 'gui',
  '硕': 'shuo shi',
  '硝': 'xiao',
  '硫': 'liu',
  '硬': 'ying',
  '确': 'que',
  '硼': 'peng',
  '碉': 'diao',
  '碌': 'lu liu',
  '碍': 'ai',
  '碎': 'sui',
  '碑': 'bei',
  '碗': 'wan',
  '碘': 'dian',
  '碟': 'die',
  '碧': 'bi',
  '碰': 'peng',
  '碱': 'jian',
  '碳': 'tan',
  '碴': 'cha',
  '碾': 'nian',
  '磁': 'ci',
  '磅': 'bang pang',
  '磕': 'ke',
  '磨': 'mo',
  '磷': 'lin',
  '磺': 'huang',
  '礁': 'jiao',
  '示': 'shi',
  '礼': 'li',
  '社': 'she',
  '祈': 'qi',
  '祖': 'zu',
  '祝': 'zhu',
  '神': 'shen',
  '祟': 'sui',
  '祠': 'ci',
  '祥': 'xiang',
  '票': 'piao',
  '祭': 'ji zhai',
  '祷': 'dao',
  '祸': 'huo',
  '禀': 'bing',
  '禁': 'jin',
  '福': 'fu',
  '离': 'li',
  '禽': 'qin',
  '禾': 'he',
  '秀': 'xiu',
  '私': 'si',
  '秃': 'tu',
  '秆': 'gan',
  '秉': 'bing',
  '秋': 'qiu',
  '种': 'zhong chong',
  '科': 'ke',
  '秒': 'miao',
  '秕': 'bi',
  '秘': 'mi bi',
  '租': 'zu',
  '秤': 'cheng',
  '秦': 'qin',
  '秧': 'yang',
  '秩': 'zhi',
  '秫': 'shu',
  '积': 'ji',
  '称': 'cheng chen',
  '秸': 'jie',
  '移': 'yi',
  '秽': 'hui',
  '稀': 'xi',
  '程': 'cheng',
  '稍': 'shao',
  '税': 'shui',
  '稚': 'zhi',
  '稠': 'chou',
  '稳': 'wen',
  '稻': 'dao',
  '稼': 'jia',
  '稽': 'ji qi',
  '稿': 'gao',
  '穆': 'mu',
  '穗': 'sui',
  '穴': 'xue',
  '究': 'jiu',
  '穷': 'qiong',
  '空': 'kong',
  '穿': 'chuan',
  '突': 'tu',
  '窃': 'qie',
  '窄': 'zhai',
  '窍': 'qiao',
  '窑': 'yao',
  '窒': 'zhi',
  '窖': 'jiao',
  '窗': 'chuang',
  '窘': 'jiong',
  '窜': 'cuan',
  '窝': 'wo',
  '窟': 'ku',
  '窥': 'kui',
  '窿': 'long',
  '立': 'li',
  '竖': 'shu',
  '站': 'zhan',
  '竞': 'jing',
  '竟': 'jing',
  '章': 'zhang',
  '竣': 'jun',
  '童': 'tong',
  '竭': 'jie',
  '端': 'duan',
  '竹': 'zhu',
  '竿': 'gan',
  '笆': 'ba',
  '笋': 'sun',
  '笑': 'xiao',
  '笔': 'bi',
  '笙': 'sheng',
  '笛': 'di',
  '笤': 'tiao',
  '符': 'fu',
  '笨': 'ben',
  '第': 'di',
  '笼': 'long',
  '等': 'deng',
  '筋': 'jin',
  '筏': 'fa',
  '筐': 'kuang',
  '筑': 'zhu',
  '筒': 'tong',
  '答': 'da',
  '策': 'ce',
  '筛': 'shai',
  '筝': 'zheng',
  '筷': 'kuai',
  '筹': 'chou',
  '签': 'qian',
  '简': 'jian',
  '箍': 'gu',
  '箕': 'ji',
  '算': 'suan',
  '管': 'guan',
  '箩': 'luo',
  '箫': 'xiao',
  '箭': 'jian',
  '箱': 'xiang',
  '篇': 'pian',
  '篓': 'lou',
  '篙': 'gao',
  '篡': 'cuan',
  '篮': 'lan',
  '篱': 'li',
  '篷': 'peng',
  '簇': 'cu',
  '簸': 'bo',
  '簿': 'bo bu',
  '籍': 'ji',
  '米': 'mi',
  '类': 'lei',
  '籽': 'zi',
  '粉': 'fen',
  '粒': 'li',
  '粗': 'cu',
  '粘': 'nian zhan',
  '粟': 'su',
  '粤': 'yue',
  '粥': 'zhou yu',
  '粪': 'fen',
  '粮': 'liang',
  '粱': 'liang',
  '粹': 'cui',
  '精': 'jing',
  '糊': 'hu',
  '糕': 'gao',
  '糖': 'tang',
  '糙': 'cao',
  '糜': 'mi mei',
  '糟': 'zao',
  '糠': 'kang',
  '糯': 'nuo',
  '系': 'xi ji',
  '紊': 'wen',
  '素': 'su',
  '索': 'suo',
  '紧': 'jin',
  '紫': 'zi',
  '累': 'lei',
  '絮': 'xu',
  '繁': 'fan po',
  '纠': 'jiu',
  '红': 'hong gong',
  '纤': 'xian qian',
  '约': 'yue yao',
  '级': 'ji',
  '纪': 'ji',
  '纫': 'ren',
  '纬': 'wei',
  '纯': 'chun',
  '纱': 'sha',
  '纲': 'gang',
  '纳': 'na',
  '纵': 'zong',
  '纷': 'fen',
  '纸': 'zhi',
  '纹': 'wen',
  '纺': 'fang',
  '纽': 'niu',
  '线': 'xian',
  '练': 'lian',
  '组': 'zu',
  '绅': 'shen',
  '细': 'xi',
  '织': 'zhi',
  '终': 'zhong',
  '绊': 'ban',
  '绍': 'shao',
  '绎': 'yi',
  '经': 'jing',
  '绑': 'bang',
  '绒': 'rong',
  '结': 'jie',
  '绕': 'rao',
  '绘': 'hui',
  '给': 'gei ji',
  '络': 'luo lao',
  '绝': 'jue',
  '绞': 'jiao',
  '统': 'tong',
  '绢': 'juan',
  '绣': 'xiu',
  '继': 'ji',
  '绩': 'ji',
  '绪': 'xu',
  '续': 'xu',
  '绰': 'chuo chao',
  '绳': 'sheng',
  '维': 'wei',
  '绵': 'mian',
  '绷': 'beng',
  '绸': 'chou',
  '综': 'zong zeng',
  '绽': 'zhan',
  '绿': 'lv lu',
  '缀': 'zhui',
  '缅': 'mian',
  '缆': 'lan',
  '缎': 'duan',
  '缓': 'huan',
  '缔': 'di',
  '缕': 'lv',
  '编': 'bian',
  '缘': 'yuan',
  '缚': 'fu',
  '缝': 'feng',
  '缠': 'chan',
  '缤': 'bin',
  '缨': 'ying',
  '缩': 'suo su',
  '缭': 'liao',
  '缰': 'jiang',
  '缴': 'jiao zhuo',
  '缸': 'gang',
  '缺': 'que',
  '罐': 'guan',
  '网': 'wang',
  '罕': 'han',
  '罗': 'luo',
  '罚': 'fa',
  '罢': 'ba pi',
  '罩': 'zhao',
  '罪': 'zui',
  '置': 'zhi',
  '署': 'shu',
  '羊': 'yang xiang',
  '美': 'mei',
  '羔': 'gao',
  '羞': 'xiu',
  '羡': 'xian',
  '群': 'qun',
  '羹': 'geng',
  '羽': 'yu',
  '翁': 'weng',
  '翅': 'chi',
  '翎': 'ling',
  '翔': 'xiang',
  '翘': 'qiao',
  '翠': 'cui',
  '翩': 'pian',
  '翰': 'han',
  '翻': 'fan',
  '翼': 'yi',
  '耀': 'yao',
  '老': 'lao',
  '考': 'kao',
  '者': 'zhe',
  '而': 'er',
  '耍': 'shua',
  '耐': 'nai',
  '耕': 'geng',
  '耗': 'hao',
  '耘': 'yun',
  '耙': 'pa ba',
  '耳': 'er',
  '耸': 'song',
  '耻': 'chi',
  '耽': 'dan',
  '耿': 'geng',
  '聂': 'nie',
  '聊': 'liao',
  '聋': 'long',
  '职': 'zhi',
  '联': 'lian',
  '聘': 'pin',
  '聚': 'ju',
  '聪': 'cong',
  '肃': 'su',
  '肄': 'yi',
  '肆': 'si',
  '肉': 'rou',
  '肋': 'lei le',
  '肌': 'ji',
  '肖': 'xiao',
  '肘': 'zhou',
  '肚': 'du',
  '肛': 'gang',
  '肝': 'gan',
  '肠': 'chang',
  '股': 'gu',
  '肢': 'zhi',
  '肤': 'fu',
  '肥': 'fei',
  '肩': 'jian',
  '肪': 'fang',
  '肮': 'ang',
  '肯': 'ken',
  '育': 'yu yo',
  '肴': 'yao',
  '肺': 'fei',
  '肾': 'shen',
  '肿': 'zhong',
  '胀': 'zhang',
  '胁': 'xie',
  '胃': 'wei',
  '胆': 'dan',
  '背': 'bei',
  '胎': 'tai',
  '胖': 'pang pan',
  '胚': 'pei',
  '胜': 'sheng',
  '胞': 'bao',
  '胡': 'hu',
  '胧': 'long',
  '胯': 'kua',
  '胰': 'yi',
  '胳': 'ge ga',
  '胶': 'jiao',
  '胸': 'xiong',
  '能': 'neng nai',
  '脂': 'zhi',
  '脆': 'cui',
  '脉': 'mai mo',
  '脊': 'ji',
  '脏': 'zang',
  '脐': 'qi',
  '脑': 'nao',
  '脓': 'nong',
  '脖': 'bo',
  '脚': 'jiao jue',
  '脯': 'pu fu',
  '脱': 'tuo',
  '脸': 'lian',
  '脾': 'pi',
  '腊': 'la xi',
  '腋': 'ye',
  '腌': 'yan a',
  '腐': 'fu',
  '腔': 'qiang',
  '腕': 'wan',
  '腥': 'xing',
  '腮': 'sai',
  '腰': 'yao',
  '腹': 'fu',
  '腺': 'xian',
  '腻': 'ni',
  '腾': 'teng',
  '腿': 'tui',
  '膀': 'bang pang',
  '膊': 'bo',
  '膏': 'gao',
  '膘': 'biao',
  '膛': 'tang',
  '膜': 'mo',
  '膝': 'xi',
  '膨': 'peng',
  '膳': 'shan',
  '臀': 'tun',
  '臂': 'bi bei',
  '臊': 'sao',
  '臣': 'chen',
  '自': 'zi',
  '臭': 'chou xiu',
  '至': 'zhi',
  '致': 'zhi',
  '臼': 'jiu',
  '舀': 'yao',
  '舅': 'jiu',
  '舆': 'yu',
  '舌': 'she',
  '舍': 'she',
  '舒': 'shu',
  '舔': 'tian',
  '舞': 'wu',
  '舟': 'zhou',
  '航': 'hang',
  '般': 'ban bo pan',
  '舰': 'jian',
  '舱': 'cang',
  '舵': 'duo',
  '舶': 'bo',
  '舷': 'xian',
  '船': 'chuan',
  '艇': 'ting',
  '艘': 'sou',
  '良': 'liang',
  '艰': 'jian',
  '色': 'se shai',
  '艳': 'yan',
  '艺': 'yi',
  '艾': 'ai yi',
  '节': 'jie',
  '芋': 'yu',
  '芍': 'shao que',
  '芒': 'mang',
  '芙': 'fu',
  '芜': 'wu',
  '芝': 'zhi',
  '芥': 'jie gai',
  '芦': 'lu',
  '芬': 'fen',
  '芭': 'ba',
  '芯': 'xin',
  '花': 'hua',
  '芳': 'fang',
  '芹': 'qin',
  '芽': 'ya',
  '苇': 'wei',
  '苍': 'cang',
  '苏': 'su',
  '苔': 'tai',
  '苗': 'miao',
  '苛': 'ke he',
  '苞': 'bao',
  '苟': 'gou',
  '若': 'ruo re',
  '苦': 'ku',
  '苫': 'shan',
  '英': 'ying',
  '苹': 'ping peng',
  '茁': 'zhuo',
  '茂': 'mao',
  '范': 'fan',
  '茄': 'qie jia',
  '茅': 'mao',
  '茉': 'mo',
  '茎': 'jing',
  '茧': 'jian',
  '茫': 'mang',
  '茬': 'cha',
  '茴': 'hui',
  '茵': 'yin',
  '茶': 'cha',
  '茸': 'rong',
  '荆': 'jing',
  '草': 'cao',
  '荐': 'jian',
  '荒': 'huang',
  '荔': 'li',
  '荚': 'jia',
  '荞': 'qiao',
  '荠': 'qi ji',
  '荡': 'dang',
  '荣': 'rong',
  '荤': 'hun',
  '荧': 'ying',
  '药': 'yao',
  '荷': 'he',
  '荸': 'bi',
  '莉': 'li',
  '莫': 'mo mu',
  '莱': 'lai',
  '莲': 'lian',
  '获': 'huo',
  '莹': 'ying',
  '莺': 'ying',
  '莽': 'mang',
  '菇': 'gu',
  '菊': 'ju',
  '菌': 'jun',
  '菜': 'cai',
  '菠': 'bo',
  '菩': 'pu',
  '菱': 'ling',
  '菲': 'fei',
  '萄': 'tao',
  '萌': 'meng',
  '萍': 'ping',
  '萎': 'wei',
  '萝': 'luo',
  '萤': 'ying',
  '营': 'ying',
  '萧': 'xiao',
  '萨': 'sa',
  '落': 'luo la lao',
  '著': 'zhu zhuo zhe',
  '葛': 'ge',
  '葡': 'pu',
  '董': 'dong',
  '葫': 'hu',
  '葬': 'zang',
  '葱': 'cong',
  '葵': 'kui',
  '蒂': 'di',
  '蒋': 'jiang',
  '蒙': 'meng',
  '蒜': 'suan',
  '蒲': 'pu',
  '蒸': 'zheng',
  '蒿': 'hao',
  '蓄': 'xu',
  '蓉': 'rong',
  '蓖': 'bi',
  '蓝': 'lan',
  '蓬': 'peng',
  '蔑': 'mie',
  '蔓': 'man wan',
  '蔗': 'zhe',
  '蔚': 'wei yu',
  '蔫': 'nian',
  '蔬': 'shu',
  '蔼': 'ai',
  '蔽': 'bi',
  '蕉': 'jiao',
  '蕊': 'rui',
  '蕴': 'yun',
  '蕾': 'lei',
  '薄': 'bao bo',
  '薇': 'wei',
  '薛': 'xue',
  '薪': 'xin',
  '薯': 'shu',
  '藏': 'cang zang',
  '藐': 'miao',
  '藕': 'ou',
  '藤': 'teng',
  '藻': 'zao',
  '蘑': 'mo',
  '蘸': 'zhan',
  '虎': 'hu',
  '虏': 'lu',
  '虐': 'nve',
  '虑': 'lv',
  '虚': 'xu',
  '虫': 'chong',
  '虱': 'shi',
  '虹': 'hong jiang',
  '虽': 'sui',
  '虾': 'xia ha',
  '蚀': 'shi',
  '蚁': 'yi',
  '蚂': 'ma',
  '蚊': 'wen',
  '蚌': 'bang beng',
  '蚓': 'yin',
  '蚕': 'can',
  '蚜': 'ya',
  '蚣': 'gong zhong',
  '蚤': 'zao',
  '蚪': 'dou',
  '蚯': 'qiu',
  '蛀': 'zhu',
  '蛆': 'qu',
  '蛇': 'she yi',
  '蛉': 'ling',
  '蛋': 'dan',
  '蛔': 'hui',
  '蛙': 'wa',
  '蛛': 'zhu',
  '蛤': 'ha ge',
  '蛮': 'man',
  '蛹': 'yong',
  '蛾': 'e yi',
  '蜀': 'shu',
  '蜂': 'feng',
  '蜈': 'wu',
  '蜒': 'yan',
  '蜓': 'ting',
  '蜕': 'tui',
  '蜗': 'wo',
  '蜘': 'zhi',
  '蜜': 'mi',
  '蜡': 'la zha',
  '蜻': 'qing',
  '蝇': 'ying',
  '蝉': 'chan',
  '蝌': 'ke',
  '蝎': 'xie',
  '蝗': 'huang',
  '蝙': 'bian',
  '蝠': 'fu',
  '蝴': 'hu',
  '蝶': 'die',
  '螃': 'pang',
  '融': 'rong',
  '螟': 'ming',
  '螺': 'luo',
  '蟀': 'shuai',
  '蟆': 'ma mo',
  '蟋': 'xi',
  '蟹': 'xie',
  '蠕': 'ru',
  '蠢': 'chun',
  '血': 'xue xie',
  '衅': 'xin',
  '行': 'xing hang heng',
  '衍': 'yan',
  '衔': 'xian',
  '街': 'jie',
  '衙': 'ya',
  '衡': 'heng',
  '衣': 'yi',
  '补': 'bu',
  '表': 'biao',
  '衩': 'cha',
  '衫': 'shan',
  '衬': 'chen',
  '衰': 'shuai cui',
  '衷': 'zhong',
  '袁': 'yuan',
  '袄': 'ao',
  '袋': 'dai',
  '袍': 'pao',
  '袒': 'tan',
  '袖': 'xiu',
  '袜': 'wa',
  '被': 'bei pi',
  '袭': 'xi',
  '袱': 'fu',
  '裁': 'cai',
  '裂': 'lie',
  '装': 'zhuang',
  '裆': 'dang',
  '裕': 'yu',
  '裙': 'qun',
  '裤': 'ku',
  '裳': 'shang chang',
  '裸': 'luo',
  '裹': 'guo',
  '褂': 'gua',
  '褐': 'he',
  '褒': 'bao',
  '褥': 'ru',
  '褪': 'tui tun',
  '襟': 'jin',
  '西': 'xi',
  '要': 'yao',
  '覆': 'fu',
  '见': 'jian xian',
  '观': 'guan',
  '规': 'gui',
  '觅': 'mi',
  '视': 'shi',
  '览': 'lan',
  '觉': 'jue jiao',
  '角': 'jiao jue',
  '解': 'jie xie',
  '触': 'chu',
  '言': 'yan',
  '誉': 'yu',
  '誊': 'teng',
  '誓': 'shi',
  '警': 'jing',
  '譬': 'pi',
  '计': 'ji',
  '订': 'ding',
  '认': 'ren',
  '讥': 'ji',
  '讨': 'tao',
  '让': 'rang',
  '训': 'xun',
  '议': 'yi',
  '讯': 'xun',
  '记': 'ji',
  '讲': 'jiang',
  '讳': 'hui',
  '讶': 'ya',
  '许': 'xu hu',
  '讹': 'e',
  '论': 'lun',
  '讼': 'song',
  '讽': 'feng',
  '设': 'she',
  '访': 'fang',
  '诀': 'jue',
  '证': 'zheng',
  '评': 'ping',
  '诅': 'zu',
  '识': 'shi zhi',
  '诈': 'zha',
  '诉': 'su',
  '诊': 'zhen',
  '词': 'ci',
  '译': 'yi',
  '试': 'shi',
  '诗': 'shi',
  '诚': 'cheng',
  '话': 'hua',
  '诞': 'dan',
  '诡': 'gui',
  '询': 'xun',
  '该': 'gai',
  '详': 'xiang yang',
  '诫': 'jie',
  '诬': 'wu',
  '语': 'yu',
  '误': 'wu',
  '诱': 'you',
  '诲': 'hui',
  '说': 'shuo shui yue',
  '诵': 'song',
  '请': 'qing',
  '诸': 'zhu',
  '诺': 'nuo',
  '读': 'du dou',
  '诽': 'fei',
  '课': 'ke',
  '谁': 'shui shei',
  '调': 'tiao diao zhou',
  '谅': 'liang',
  '谆': 'zhun',
  '谈': 'tan',
  '谊': 'yi',
  '谋': 'mou',
  '谍': 'die',
  '谎': 'huang',
  '谐': 'xie',
  '谒': 'ye',
  '谓': 'wei',
  '谚': 'yan',
  '谜': 'mi mei',
  '谢': 'xie',
  '谣': 'yao',
  '谤': 'bang',
  '谦': 'qian',
  '谨': 'jin',
  '谬': 'miu',
  '谭': 'tan',
  '谱': 'pu',
  '谴': 'qian',
  '谷': 'gu yu',
  '豁': 'huo hua',
  '豆': 'dou',
  '豌': 'wan',
  '象': 'xiang',
  '豪': 'hao',
  '豫': 'yu',
  '豹': 'bao',
  '豺': 'chai',
  '貌': 'mao',
  '贝': 'bei',
  '贞': 'zhen',
  '负': 'fu',
  '贡': 'gong',
  '财': 'cai',
  '责': 'ze zhai',
  '贤': 'xian',
  '败': 'bai',
  '账': 'zhang',
  '货': 'huo',
  '质': 'zhi',
  '贩': 'fan',
  '贪': 'tan',
  '贫': 'pin',
  '贬': 'bian',
  '购': 'gou',
  '贮': 'zhu',
  '贯': 'guan',
  '贰': 'er',
  '贱': 'jian',
  '贴': 'tie',
  '贵': 'gui',
  '贷': 'dai',
  '贸': 'mao',
  '费': 'fei',
  '贺': 'he',
  '贼': 'zei',
  '贾': 'jia gu',
  '贿': 'hui',
  '赁': 'lin',
  '赂': 'lu',
  '赃': 'zang',
  '资': 'zi',
  '赊': 'she',
  '赋': 'fu',
  '赌': 'du',
  '赎': 'shu',
  '赏': 'shang',
  '赐': 'ci',
  '赔': 'pei',
  '赖': 'lai',
  '赘': 'zhui',
  '赚': 'zhuan zuan',
  '赛': 'sai',
  '赞': 'zan',
  '赠': 'zeng',
  '赡': 'shan',
  '赢': 'ying',
  '赤': 'chi',
  '赦': 'she',
  '赫': 'he',
  '走': 'zou',
  '赴': 'fu',
  '赵': 'zhao',
  '赶': 'gan',
  '起': 'qi',
  '趁': 'chen',
  '超': 'chao',
  '越': 'yue',
  '趋': 'qu cu',
  '趟': 'tang',
  '趣': 'qu cu',
  '足': 'zu',
  '趴': 'pa',
  '趾': 'zhi',
  '跃': 'yue',
  '跋': 'ba',
  '跌': 'die',
  '跑': 'pao',
  '跛': 'bo',
  '距': 'ju',
  '跟': 'gen',
  '跨': 'kua',
  '跪': 'gui',
  '路': 'lu',
  '跳': 'tiao tao',
  '践': 'jian',
  '跷': 'qiao',
  '跺': 'duo',
  '踊': 'yong',
  '踏': 'ta',
  '踢': 'ti',
  '踩': 'cai',
  '踪': 'zong',
  '踱': 'duo',
  '蹂': 'rou',
  '蹄': 'ti',
  '蹈': 'dao',
  '蹋': 'ta',
  '蹦': 'beng',
  '蹬': 'deng',
  '蹭': 'ceng',
  '蹲': 'dun cun',
  '躁': 'zao',
  '躏': 'lin',
  '身': 'shen',
  '躬': 'gong',
  '躯': 'qu',
  '躲': 'duo',
  '躺': 'tang',
  '车': 'che ju',
  '轧': 'ya zha ga',
  '轨': 'gui',
  '轩': 'xuan',
  '转': 'zhuan zhuai',
  '轮': 'lun',
  '软': 'ruan',
  '轰': 'hong',
  '轴': 'zhou',
  '轻': 'qing',
  '载': 'zai',
  '轿': 'jiao',
  '较': 'jiao',
  '辅': 'fu',
  '辆': 'liang',
  '辈': 'bei',
  '辉': 'hui',
  '辐': 'fu',
  '辑': 'ji',
  '输': 'shu',
  '辕': 'yuan',
  '辖': 'xia',
  '辙': 'zhe',
  '辛': 'xin',
  '辜': 'gu',
  '辞': 'ci',
  '辟': 'pi bi',
  '辣': 'la',
  '辨': 'bian',
  '辩': 'bian',
  '辫': 'bian',
  '辰': 'chen',
  '辱': 'ru',
  '边': 'bian',
  '辽': 'liao',
  '达': 'da',
  '迁': 'qian',
  '迂': 'yu',
  '迄': 'qi',
  '迅': 'xun',
  '过': 'guo',
  '迈': 'mai',
  '迎': 'ying',
  '运': 'yun',
  '近': 'jin',
  '返': 'fan',
  '还': 'hai huan',
  '这': 'zhe zhei',
  '进': 'jin',
  '远': 'yuan',
  '违': 'wei',
  '连': 'lian',
  '迟': 'chi',
  '迫': 'po pai',
  '述': 'shu',
  '迷': 'mi',
  '迹': 'ji',
  '追': 'zhui dui',
  '退': 'tui',
  '送': 'song',
  '适': 'shi kuo',
  '逃': 'tao',
  '逆': 'ni',
  '选': 'xuan',
  '逊': 'xun',
  '透': 'tou',
  '逐': 'zhu',
  '递': 'di',
  '途': 'tu',
  '逗': 'dou',
  '通': 'tong',
  '逛': 'guang',
  '逝': 'shi',
  '逞': 'cheng',
  '速': 'su',
  '造': 'zao',
  '逢': 'feng',
  '逮': 'dai',
  '逸': 'yi',
  '逻': 'luo',
  '逼': 'bi',
  '逾': 'yu',
  '遂': 'sui',
  '遇': 'yu',
  '遍': 'bian',
  '遏': 'e',
  '道': 'dao',
  '遗': 'yi wei',
  '遣': 'qian',
  '遥': 'yao',
  '遭': 'zao',
  '遮': 'zhe',
  '遵': 'zun',
  '避': 'bi',
  '邀': 'yao',
  '邑': 'yi',
  '邓': 'deng',
  '邢': 'xing',
  '那': 'na nei',
  '邦': 'bang',
  '邪': 'xie ya ye yu xu',
  '邮': 'you',
  '邻': 'lin',
  '郁': 'yu',
  '郊': 'jiao',
  '郎': 'lang',
  '郑': 'zheng',
  '部': 'bu',
  '郭': 'guo',
  '都': 'dou du',
  '鄙': 'bi',
  '酌': 'zhuo',
  '配': 'pei',
  '酒': 'jiu',
  '酗': 'xu',
  '酝': 'yun',
  '酣': 'han',
  '酥': 'su',
  '酪': 'lao',
  '酬': 'chou',
  '酱': 'jiang',
  '酵': 'jiao',
  '酷': 'ku',
  '酸': 'suan',
  '酿': 'niang',
  '醇': 'chun',
  '醉': 'zui',
  '醋': 'cu',
  '醒': 'xing',
  '采': 'cai',
  '释': 'shi',
  '里': 'li',
  '重': 'zhong chong',
  '野': 'ye',
  '量': 'liang',
  '金': 'jin',
  '鉴': 'jian',
  '针': 'zhen',
  '钉': 'ding',
  '钓': 'diao',
  '钙': 'gai',
  '钝': 'dun',
  '钞': 'chao',
  '钟': 'zhong',
  '钠': 'na',
  '钢': 'gang',
  '钥': 'yao yue',
  '钦': 'qin',
  '钧': 'jun',
  '钩': 'gou',
  '钮': 'niu',
  '钱': 'qian',
  '钳': 'qian',
  '钻': 'zuan',
  '钾': 'jia',
  '铁': 'tie',
  '铃': 'ling',
  '铅': 'qian yan',
  '铆': 'mao',
  '铐': 'kao',
  '铛': 'dang cheng',
  '铜': 'tong',
  '铝': 'lv',
  '铡': 'zha',
  '铣': 'xian xi',
  '铭': 'ming',
  '铲': 'chan',
  '银': 'yin',
  '铸': 'zhu',
  '铺': 'pu',
  '链': 'lian',
  '销': 'xiao',
  '锁': 'suo',
  '锄': 'chu',
  '锅': 'guo',
  '锈': 'xiu',
  '锉': 'cuo',
  '锋': 'feng',
  '锌': 'xin',
  '锐': 'rui',
  '错': 'cuo',
  '锚': 'mao',
  '锡': 'xi',
  '锣': 'luo',
  '锤': 'chui',
  '锥': 'zhui',
  '锦': 'jin',
  '锨': 'xian',
  '锭': 'ding',
  '键': 'jian',
  '锯': 'ju',
  '锰': 'meng',
  '锹': 'qiao',
  '锻': 'duan',
  '镀': 'du',
  '镇': 'zhen',
  '镊': 'nie',
  '镐': 'hao gao',
  '镜': 'jing',
  '镣': 'liao',
  '镰': 'lian',
  '镶': 'xiang',
  '长': 'chang zhang',
  '门': 'men',
  '闪': 'shan',
  '闭': 'bi',
  '问': 'wen',
  '闯': 'chuang',
  '闰': 'run',
  '闲': 'xian',
  '间': 'jian',
  '闷': 'men',
  '闸': 'zha',
  '闹': 'nao',
  '闺': 'gui',
  '闻': 'wen',
  '闽': 'min',
  '阀': 'fa',
  '阁': 'ge',
  '阅': 'yue',
  '阎': 'yan',
  '阐': 'chan',
  '阔': 'kuo',
  '队': 'dui',
  '阱': 'jing',
  '防': 'fang',
  '阳': 'yang',
  '阴': 'yin',
  '阵': 'zhen',
  '阶': 'jie',
  '阻': 'zu',
  '阿': 'a e',
  '附': 'fu',
  '际': 'ji',
  '陆': 'lu liu',
  '陈': 'chen',
  '陋': 'lou',
  '陌': 'mo',
  '降': 'jiang xiang',
  '限': 'xian',
  '陕': 'shan',
  '陡': 'dou',
  '院': 'yuan',
  '除': 'chu',
  '陨': 'yun',
  '险': 'xian',
  '陪': 'pei',
  '陵': 'ling',
  '陶': 'tao yao',
  '陷': 'xian',
  '隅': 'yu',
  '隆': 'long',
  '随': 'sui',
  '隐': 'yin',
  '隔': 'ge',
  '隘': 'ai',
  '隙': 'xi',
  '障': 'zhang',
  '隧': 'sui',
  '隶': 'li',
  '难': 'nan nuo',
  '雀': 'que qiao',
  '雁': 'yan',
  '雄': 'xiong',
  '雅': 'ya',
  '集': 'ji',
  '雇': 'gu',
  '雌': 'ci',
  '雏': 'chu',
  '雕': 'diao',
  '雨': 'yu',
  '雪': 'xue',
  '雳': 'li',
  '零': 'ling',
  '雷': 'lei',
  '雹': 'bao',
  '雾': 'wu',
  '需': 'xu',
  '震': 'zhen',
  '霉': 'mei',
  '霍': 'huo',
  '霎': 'sha',
  '霜': 'shuang',
  '霞': 'xia',
  '露': 'lu lou',
  '霸': 'ba',
  '霹': 'pi',
  '青': 'qing',
  '靖': 'jing',
  '静': 'jing',
  '非': 'fei',
  '靠': 'kao',
  '靡': 'mi',
  '面': 'mian',
  '革': 'ge ji',
  '靴': 'xue',
  '靶': 'ba',
  '鞋': 'xie',
  '鞍': 'an',
  '鞠': 'ju',
  '鞭': 'bian',
  '韧': 'ren',
  '韩': 'han',
  '韭': 'jiu',
  '音': 'yin',
  '韵': 'yun',
  '页': 'ye',
  '顶': 'ding',
  '顷': 'qing',
  '项': 'xiang',
  '顺': 'shun',
  '须': 'xu',
  '顽': 'wan',
  '顾': 'gu',
  '顿': 'dun du',
  '颁': 'ban',
  '颂': 'song',
  '预': 'yu',
  '颅': 'lu',
  '领': 'ling',
  '颇': 'po',
  '颈': 'jing geng',
  '颊': 'jia',
  '频': 'pin bin',
  '颓': 'tui',
  '颖': 'ying',
  '颗': 'ke',
  '题': 'ti',
  '颜': 'yan',
  '额': 'e',
  '颠': 'dian',
  '颤': 'chan zhan',
  '风': 'feng',
  '飒': 'sa',
  '飘': 'piao',
  '飞': 'fei',
  '食': 'shi si yi',
  '餐': 'can',
  '饥': 'ji',
  '饭': 'fan',
  '饮': 'yin',
  '饰': 'shi',
  '饱': 'bao',
  '饲': 'si',
  '饵': 'er',
  '饶': 'rao',
  '饺': 'jiao',
  '饼': 'bing',
  '饿': 'e',
  '馁': 'nei',
  '馅': 'xian',
  '馆': 'guan',
  '馋': 'chan',
  '馍': 'mo',
  '馏': 'liu',
  '馒': 'man',
  '首': 'shou',
  '香': 'xiang',
  '马': 'ma',
  '驮': 'tuo duo',
  '驯': 'xun',
  '驰': 'chi',
  '驱': 'qu',
  '驳': 'bo',
  '驴': 'lv',
  '驶': 'shi',
  '驹': 'ju',
  '驻': 'zhu',
  '驼': 'tuo',
  '驾': 'jia',
  '骂': 'ma',
  '骄': 'jiao',
  '骆': 'luo',
  '骇': 'hai',
  '验': 'yan',
  '骏': 'jun',
  '骑': 'qi',
  '骗': 'pian',
  '骚': 'sao',
  '骡': 'luo',
  '骤': 'zhou',
  '骨': 'gu',
  '髓': 'sui',
  '高': 'gao',
  '鬓': 'bin',
  '鬼': 'gui',
  '魁': 'kui',
  '魂': 'hun',
  '魄': 'po',
  '魏': 'wei',
  '魔': 'mo',
  '鱼': 'yu',
  '鲁': 'lu',
  '鲜': 'xian',
  '鲤': 'li',
  '鲫': 'ji',
  '鲸': 'jing',
  '鳄': 'e',
  '鳍': 'qi',
  '鳖': 'bie',
  '鳞': 'lin',
  '鸟': 'niao',
  '鸠': 'jiu',
  '鸡': 'ji',
  '鸣': 'ming',
  '鸥': 'ou',
  '鸦': 'ya',
  '鸭': 'ya',
  '鸯': 'yang',
  '鸳': 'yuan',
  '鸵': 'tuo',
  '鸽': 'ge',
  '鸿': 'hong',
  '鹃': 'juan',
  '鹅': 'e',
  '鹉': 'wu',
  '鹊': 'que',
  '鹏': 'peng',
  '鹤': 'he',
  '鹦': 'ying',
  '鹰': 'ying',
  '鹿': 'lu',
  '麦': 'mai',
  '麸': 'fu',
  '麻': 'ma',
  '黄': 'huang',
  '黍': 'shu',
  '黎': 'li',
  '黑': 'hei',
  '黔': 'qian',
  '默': 'mo',
  '鼎': 'ding',
  '鼓': 'gu',
  '鼠': 'shu',
  '鼻': 'bi',
  '齐': 'qi ji zi zhai',
  '齿': 'chi',
  '龄': 'ling',
  '龙': 'long',
  '龟': 'gui jun qiu',
}
